app = "lucky-stack-8002"
github = "https://github.com/nifetency/react_password_generator"
id = "7cc6e1608e25f88e6da414a67979f7868ce7f05441ce43754467c263839c281550047769a6fe6c9d98c580edbb5f7ed7"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builtin = "GitHub"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  external_port = "80"
  http_checks = []
  internal_port = "3000"
  protocol = "tcp"
  routing_policy = "latency"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [services.limits]
    cpu = "500m"
    memory = "1Gi"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.requests]
    cpu = "250m"
    memory = "512Mi"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
