app = "happy-wave-9889"
github = "https://github.com/nifetency/react_password_generator"
id = "4fbd06e6d90ba8ff03060dead2fa49b50c83e7398a31c342a83a54d27c983bbf563422e9314c72fb6bd4a3ba35b27f6c"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builtin = "GitHub"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  external_port = "80"
  http_checks = []
  internal_port = "3000"
  protocol = "tcp"
  routing_policy = "latency"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [services.limits]
    cpu = "500m"
    memory = "1Gi"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.requests]
    cpu = "250m"
    memory = "512Mi"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
