app = "pioneering-app-5760"
github = "https://github.com/nifetency/react_password_generator/archive/refs/heads/main.zip"
id = "479330a9859d6ec50f66ebf269b7051b02dd07376a72007acb10942a2801c1c667735aa9357ac862218f9cf7d1215b90"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builtin = "Github"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  external_port = "80"
  http_checks = []
  internal_port = "3000"
  protocol = "tcp"
  routing_policy = "Latency"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [services.limits]
    cpu = "1"
    memory = "256"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.requests]
    cpu = "0.5"
    memory = "128"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
