app = "swift-app-8400"
github = "https://github.com/rahul-nife/react_password_generator"
id = "01a5243eefefb2ebdc5ab040da6f0d72cfa1bc1d1836ffeb34c1d8fedce3aa4ee6364cc9d07580edfc4afa772b8042f0"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builtin = "GitHub"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  external_port = "3000"
  http_checks = []
  internal_port = "3000"
  protocol = "tcp"
  routing_policy = "latency"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [services.limits]
    cpu = "500m"
    memory = "1Gi"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.requests]
    cpu = "154m"
    memory = "358Mi"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
