name: Deploy to Nif

on:
 workflow_dispatch:  

jobs:
  deploy:
    name: Deploy to Nife
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to Nife
        uses: nifetency/nife-actions@2.4
        env:
          NIFE_ACCESS_TOKEN: ${{ secrets.NIFE_ACCESS_TOKEN }}
        with:
          args: "nifectl site redeploy --git-url https://github.com/nifetency/react_password_generator --git-branch main --git-provider github --git-token none --framework React --install "npm install" --build "npm run build" --output build -y" 
            
